In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
a=np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
b=np.ones((2,2),dtype=np.int_)
b

array([[1, 1],
       [1, 1]])

In [4]:
#random values
np.random.random((2,2))

array([[0.10558219, 0.30024808],
       [0.29293613, 0.44899375]])

In [5]:
np.random.normal(loc=0,scale=1,size=(2,2))

array([[-0.15118347,  0.04577462],
       [ 0.00691265, -1.67475671]])

In [6]:
#random integers
np.random.randint(low=0,high=10,size=(2,2))

array([[5, 6],
       [3, 6]])

In [7]:
#index of max value 
a=np.array([2,4,6,8,9,12,6,3,1])

In [8]:
np.max(a)

12

In [10]:
np.argmax(a)


5

# measure time

In [11]:
import time

In [14]:
t1=time.time()
print("pankaj")
t2=time.time()
print("time for printing is "+str(t2-t1)+ " sec")

pankaj
time for printing is 0.000297069549561 sec


# slicing

In [17]:
a=np.random.randn(5,5)
a

array([[ 0.21138567,  0.33576076,  0.12853695, -0.98451462,  0.28227426],
       [ 0.16503876, -0.43163019, -0.18792904, -1.28815291, -1.09228317],
       [ 1.42785518, -0.448376  , -1.0783353 , -0.71232632, -0.60644325],
       [ 1.21751495,  0.4803057 ,  0.76726817,  1.45793206, -0.20112578],
       [-0.85964359,  0.54375634,  0.99169013,  0.35331235,  1.20074694]])

In [18]:
a[0:2,0:2]

array([[ 0.21138567,  0.33576076],
       [ 0.16503876, -0.43163019]])

In [19]:
a[:,0:3:2]

array([[ 0.21138567,  0.12853695],
       [ 0.16503876, -0.18792904],
       [ 1.42785518, -1.0783353 ],
       [ 1.21751495,  0.76726817],
       [-0.85964359,  0.99169013]])

In [27]:
b=np.random.randn(5)
indices=np.array([1,3,4,2])
b

array([ 0.80218821, -1.31198857,  0.29615173, -0.33006069,  0.3754358 ])

In [28]:
b[indices]

array([-1.31198857, -0.33006069,  0.3754358 ,  0.29615173])

# masking

In [29]:
a=np.array([[20,30,56,87,98],[23,56,78,90,23]])

In [30]:
mean=np.mean(a)

In [32]:
a[a<mean]=0

In [33]:
a

array([[ 0,  0,  0, 87, 98],
       [ 0,  0, 78, 90,  0]])